name = "gawidget"   # ← Измени на то, что ожидает CI!

main = "src/index.ts"
compatibility_date = "2026-04-10"   # обязательно свежая дата
compatibility_flags = ["nodejs_compat"]

# KV для production
[[kv_namespaces]]
binding = "myVar"
id = "01f999166da04c68a9a10b4e33cc132d"

[env.test]
name = "gawidget-test"   # или api-test, как хочешь

[[env.test.kv_namespaces]]
binding = "myVar"
id = "01f999166da04c68a9a10b4e33cc132d"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
